services:
  nginx:
    image: nginx:latest
    ports:
      - "81:81"
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - pytorch
    restart: unless-stopped

  pytorch:
    build: .
    volumes:
      - .:/app
    ports:
      - "8001:8001"
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]